server.port=8080

spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

# ==========================
# MONGODB ATLAS CONNECTION
# ==========================
spring.data.mongodb.uri=${MONGODB_URI}
spring.data.mongodb.database=learn2play
spring.data.mongodb.auto-index-creation=true

# ==========================
# BREVO SMTP CONFIGURATION
# ==========================
spring.mail.host=smtp-relay.brevo.com
spring.mail.port=587
spring.mail.username=${BREVO_SMTP_USERNAME}
spring.mail.password=${BREVO_SMTP_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true